### ISSUE TITLE
Release 1.0.0 not pushed to CocoaPods

### ISSUE THREAD

**Issue by brennan** [segment-integrations/analytics-ios-integration-countly#3]
Latest version available on CocoaPods is 0.1.1. @ladanazita @f2prateek https://cocoapods.org/?q=segment-countly

**Comment by f2prateek** [comment]
Should probably be a JIRA ticket as well.

**Comment by ladanazita** [comment]
Tracking [here](https://segment.atlassian.net/browse/EPD-3233)

**Comment by ladanazita** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  Segment-Countly (1.0.0) successfully published
 📅  July 18th, 16:21
 🌎  https://cocoapods.org/pods/Segment-Countly
 👍  Tell your friends!
--------------------------------------------------------------------------------
